spring:
  application:
    name: cloud-errands-service-assist-get
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.38.136:3306/db_cloud_errands_assist_get?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1172477133wq
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

server:
  port: 8763

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

express:
  weight:
    level:
      0: 1.00
      1: 3.00
      2: 8.00