spring:
  application:
    name: cloud-errands-service-weixin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/