spring:
  application:
    name: cloud-errands-service-user
  zipkin:
    base-url: http://152.136.77.190:9411
  boot:
    admin:
      client:
        url: http://152.136.77.190:8084
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.38.136:3306/db_cloud_errands_user?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1172477133wq
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

server:
  port: 8773

eureka:
  client:
    service-url:
      defaultZone: http://152.136.77.190:8761/eureka/