spring:
  application:
    name: cloud-errands-service-assist-get
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.38.136:3306/db_cloud_errands_assist_get?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1172477133wq
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  rabbitmq:
    host: 188.131.244.83
    port: 5672
    username: rabbit
    password: 1172477133
  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss

server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

express:
  weight:
    level0: 1.00
    level1: 3.00
    level2: 8.00

order:
  overtime:
    cancel: 1800000
    finish: 604800000
    end: 518400000

wx:
  pay-notify:
    url: http://api.ypaot.com/api/v1/assist-get/wxpay/payNotify
  refund-notify:
    url: http://api.ypaot.com/api/v1/assist-get/wxpay/refundNotify