spring:
  application:
    name: cloud-errands-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8769

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/v1/assist-get/**
      serviceId: cloud-errands-service-assist-get
    api-b:
      path: /api/v2/assist-post/**
      serviceId: cloud-errands-service-assist-post