spring:
  application:
    name: cloud-errands-zuul
  zipkin:
    base-url: http://152.136.77.190:9411
  boot:
    admin:
      client:
        url: http://152.136.77.190:8084

server:
  port: 80

eureka:
  client:
    service-url:
      default-zone: http://152.136.77.190:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/v1/assist-get/**
      serviceId: cloud-errands-service-assist-get
    api-b:
      path: /api/v1/user/**
      serviceId: cloud-errands-service-user